version: '3'

tasks:
  deps:
    desc: "Install Go dependencies"
    cmds:
      - go mod download

  fmt:
    desc: "Format imports"
    cmds:
      - goimports -w .

  lint:
    desc: "Start lint"
    cmds:
      - golangci-lint run --config .golangci.yaml ./...
    sources:
      - "**/*.go"

  build:
    desc: "Build bin"
    cmds:
      - go build -o buildcast.exe ./cmd